/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// Static sidebars
module.exports = {
  // welcome: [
  //   'welcome',
  //   {
  //   },
  // ],

  gpm: [
    'gpm',
    {
      'Getting Started': [
        { type: 'autogenerated', dirName: 'gpm/getting-started' },
      ],
      'Packages': [
        { type: 'autogenerated', dirName: 'gpm/packages' }
      ]
    }
  ],

  modules: [
    'modules',
    {
      'gmsv_myhttp': [
        { type: 'autogenerated', dirName: 'modules/gmsv_myhttp' }
      ],
      'gmsv_fastdl': [
        { type: 'autogenerated', dirName: 'gmsv_fastdl' }
      ]
    }
  ],
};

// Automatic generating sidebars for
const fs = require('fs')
const path = require('path')

const DOCS_PATH = path.resolve(__dirname, './docs')

const dirs = fs.readdirSync(DOCS_PATH).filter(filename => {
  const p = path.resolve(DOCS_PATH, filename)
  const stats = fs.lstatSync(p)

  return stats.isDirectory() && fs.existsSync(path.resolve(p, '.autosidebar'))
})

for (const name of dirs) {
  module.exports[name] = [
    { type: 'autogenerated', dirName: name }
  ]
}