/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  welcome: [
    'welcome',
    {
      type: 'category',
      label: 'Modules',
      items: [
        { type: 'link', label: 'gmsv_myhttp', href: '/gmsv_myhttp' },
      ]
    },
  ],

  gmsv_myhttp: [
    'gmsv_myhttp/intro',
    {
      type: 'category',
      label: 'Methods',
      items: [
        { type: 'autogenerated', dirName: 'gmsv_myhttp/methods' }
      ]
    },
    {
      type: 'category',
      label: 'Libraries',
      items: [
        { type: 'autogenerated', dirName: 'gmsv_myhttp/libs' }
      ]
    },
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
